test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

r2:
  service: S3
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  region: auto
  endpoint: https://0e404eea32a2f3a7adec90377ded1d65.r2.cloudflarestorage.com
  bucket: family-recipe-assets
  force_path_style: true